language: nix
sudo: true
# 'sudo: false' == containers that start fast, but only get 4G ram;
# 'sudo: true'  == VMs that start slow, but with 8G
# ..as per:  https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
# Nixpkgs PR tests OOM with 4G: https://github.com/NixOS/nixpkgs/issues/24200

matrix:
    include:
        - os: linux
          sudo: required
          script:
              - TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}/nixpkgs ./airapkgs/maintainers/scripts/travis-nox-review-pr.sh nixpkgs-verify nixpkgs-tarball
              - TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}/nixpkgs ./airapkgs/maintainers/scripts/travis-nox-review-pr.sh nixpkgs-tarball
              - TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}/nixpkgs ./airapkgs/maintainers/scripts/travis-nox-review-pr.sh nixos-options
          env:
            - BUILD_TYPE="Test Nixpkgs evaluation & NixOS options"
