site_name: AIRA
nav:
        - Getting Started: index.md
        - Basic Usage: basic_usage.md
        - AIRA in Depth: aira_in_depth.md
        - CheatSheet: cheats.md
        - Frequently Asked Questions: faq.md
        - Contributing: contributing.md
theme: readthedocs
extra_css:
    - 'css/extra_css.css'
markdown_extensions:
        - markdown.extensions.attr_list

